export const actionType = {
    //GET

    LAY_DANH_SACH_NGUOI_DUNG: 'LAY_DANH_SACH_NGUOI_DUNG',
    LAY_DANH_SACH_LOAI_NGUOI_DUNG: 'LAY_DANH_SACH_LOAI_NGUOI_DUNG',
    TIM_KIEM_NGUOI_DUNG: 'TIM_KIEM_NGUOI_DUNG',

    //POST
    DANG_NHAP: 'DANG_NHAP',
    DANG_KY: 'DANG_KY',
    THEM_NGUOI_DUNG: 'THEM_NGUOI_DUNG',
    THONG_TIN_TAI_KHOAN: 'THONG_TIN_TAI_KHOAN',

    //DELETE
    XOA_NGUOI_DUNG: 'XOA_NGUOI_DUNG',

    //PUT
    CAP_NHAT_THONG_TIN_NGUOI_DUNG: 'CAP_NHAT_THONG_TIN_NGUOI_DUNG',

    LOAD_MANG_NGUOI_DUNG: 'LOAD_MANG_NGUOI_DUNG',

    CHINH_SUA_NGUOI_DUNG: 'CHINH_SUA_NGUOI_DUNG',

    NGUOI_DANG_NHAP:'NGUOI_DANG_NHAP',
    FETCH_USER_LOGIN : 'FETCH_USER_LOGIN',

}


