export const actionTypes =
{
  //GET
  LAY_DANH_SACH_KHOA_HOC: 'LAY_DANH_SACH_KHOA_HOC',
  TIM_KIEM_KHOA_HOC:'TIM_KIEM_KHOA_HOC',
  LAY_DANH_MUC_KHOA_HOC: 'LAY_DANH_MUC_KHOA_HOC',
  LAY_KHOA_HOC_THEO_DANH_MUC: 'LAY_KHOA_HOC_THEO_DANH_MUC',
  LAY_CHI_TIET_KHOA_HOC: 'LAY_CHI_TIET_KHOA_HOC',
  LAY_THONG_TIN_HOC_VIEN_KHOA_HOC: 'LAY_THONG_TIN_HOC_VIEN_KHOA_HOC',

  //POST
  THEM_KHOA_HOC: 'THEM_KHOA_HOC',
  GHI_DANH_KHOA_HOC: 'GHI_DANH_KHOA_HOC',
  DANG_KY_KHOA_HOC: 'DANG_KY_KHOA_HOC',
  HUY_GHI_DANH: 'HUY_GHI_DANH',
  UPLOAD_HINH_ANH_KHOAHOC: 'UPLOAD_HINH_ANH_KHOA_HOC',
  


  //DELETE
  XOA_KHOA_HOC: 'XOA_KHOA_HOC',
  //PUT
  CAP_NHAT_KHOA_HOC: 'CAP_NHAT_KHOA_HOC',
  LOAD_MANG_KHOA_HOC:'LOAD_MANG_KHOA_HOC',
  CHINH_SUA_KHOA_HOC:'CHINH_SUA_KHOA_HOC'


} 